CREATE OR REPLACE DATABASE ECONOMIC_RAG_DB;
CREATE OR REPLACE SCHEMA RAW_DATA;
CREATE OR REPLACE SCHEMA CHUNKS;
CREATE OR REPLACE WAREHOUSE RAG_WH 
  WITH WAREHOUSE_SIZE = 'MEDIUM' 
  AUTO_SUSPEND = 300 
  AUTO_RESUME = TRUE 
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON DATABASE ECONOMIC_RAG_DB TO ROLE PUBLIC;  -- or your role
GRANT USAGE ON SCHEMA ECONOMIC_RAG_DB.RAW_DATA TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA ECONOMIC_RAG_DB.CHUNKS TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE RAG_WH TO ROLE PUBLIC;

SHOW SCHEMAS IN DATABASE SNOWFLAKE_PUBLIC_DATA_FREE;  -- note the schemas (e.g. SEC, ECONOMICS, GOVERNMENT)
SELECT * FROM SNOWFLAKE_PUBLIC_DATA_FREE.INFORMATION_SCHEMA.TABLES LIMIT 20;  -- find tables with text columns

-- 2. Modified query WITH WHERE clause (exactly as you asked) — only ECONOMICS schema + tables containing "INDICATORS"
SELECT *
FROM SNOWFLAKE_PUBLIC_DATA_FREE.INFORMATION_SCHEMA.TABLES
WHERE 
    -- TABLE_SCHEMA = 'ECONOMICS'
   TABLE_NAME LIKE '%INDICATORS%'
LIMIT 20;

-- 1. Check ALL columns in the main ATTRIBUTES table (this is the one most likely to have text descriptions)
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COMMENT
FROM SNOWFLAKE_PUBLIC_DATA_FREE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES'
ORDER BY ORDINAL_POSITION;

-- 2. Sample the actual data from the same table (run this to see if there are long text fields)
SELECT * 
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES 
LIMIT 15;

-- 3. Also run this for the VINTAGE version (same schema)
SELECT *
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES_VINTAGE
LIMIT 10;

-- 2. Load from the main ATTRIBUTES table (rich text via concatenation)
INSERT INTO ECONOMIC_RAG_DB.RAW_DATA.RAW_ECONOMIC_TEXT 
  (SOURCE, COMPANY_OR_ENTITY, FILING_TYPE_OR_CATEGORY, DATE, TEXT_CONTENT)
SELECT 
  'FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES',
  VARIABLE,
  RELEASE_NAME,
  NULL,
  CONCAT(
    VARIABLE_NAME, 
    ' | Measure: ', MEASURE,
    ' | Measurement Type: ', MEASUREMENT_TYPE,
    ' | Industry: ', INDUSTRY,
    ' | Unit: ', UNIT,
    ' | Frequency: ', FREQUENCY,
    ' | Release: ', RELEASE_NAME,
    ' | Seasonally Adjusted: ', SEASONALLY_ADJUSTED
  ) AS TEXT_CONTENT
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES
WHERE VARIABLE_NAME IS NOT NULL
  AND LENGTH(VARIABLE_NAME) > 50;

  -- 3. Load from the VINTAGE table (adds more descriptive rows)
INSERT INTO ECONOMIC_RAG_DB.RAW_DATA.RAW_ECONOMIC_TEXT 
  (SOURCE, COMPANY_OR_ENTITY, FILING_TYPE_OR_CATEGORY, DATE, TEXT_CONTENT)
SELECT 
  'FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES_VINTAGE',
  VARIABLE,
  RELEASE_NAME,
  NULL,
  CONCAT(
    VARIABLE_NAME, 
    ' | Measure: ', MEASURE,
    ' | Measurement Type: ', MEASUREMENT_TYPE,
    ' | Industry: ', INDUSTRY,
    ' | Unit: ', UNIT,
    ' | Frequency: ', FREQUENCY,
    ' | Release: ', RELEASE_NAME,
    ' | Seasonally Adjusted: ', SEASONALLY_ADJUSTED
  ) AS TEXT_CONTENT
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FINANCIAL_ECONOMIC_INDICATORS_ATTRIBUTES_VINTAGE
WHERE VARIABLE_NAME IS NOT NULL
  AND LENGTH(VARIABLE_NAME) > 50;

  -- 4. Verify how many rows we loaded
SELECT 
  SOURCE,
  COUNT(*) as row_count,
  COUNT(DISTINCT COMPANY_OR_ENTITY) as unique_variables
FROM ECONOMIC_RAG_DB.RAW_DATA.RAW_ECONOMIC_TEXT 
GROUP BY SOURCE;

USE DATABASE ECONOMIC_RAG_DB;
CREATE OR REPLACE SCHEMA CHUNKS;
CREATE OR REPLACE STAGE RAW_DATA;

USE DATABASE ECONOMIC_RAG_DB;
USE SCHEMA RAW_DATA;
CREATE OR REPLACE STAGE CHUNK_STAGE;

SELECT COUNT(*) as total_chunks FROM ECONOMIC_RAG_DB.CHUNKS.ECONOMIC_CHUNKS;
SELECT * FROM ECONOMIC_RAG_DB.CHUNKS.ECONOMIC_CHUNKS LIMIT 5;