-- 1. Set correct context
USE DATABASE ECONOMIC_RAG_DB;
USE SCHEMA CHUNKS;

-- 2. Create the Cortex Search Service (uses Arctic Embed automatically)
CREATE OR REPLACE CORTEX SEARCH SERVICE ECONOMIC_RAG_SEARCH
  ON CHUNK_TEXT
  ATTRIBUTES 
    SOURCE,
    COMPANY_OR_ENTITY,
    FILING_TYPE_OR_CATEGORY,
    DATE
  WAREHOUSE = RAG_WH
  TARGET_LAG = '5 minutes'          -- ← THIS WAS MISSING
AS
SELECT 
  CHUNK_TEXT,
  SOURCE,
  COMPANY_OR_ENTITY,
  FILING_TYPE_OR_CATEGORY,
  DATE,
  CHUNK_ID
FROM ECONOMIC_RAG_DB.CHUNKS.ECONOMIC_CHUNKS;

-- 3. Check status (run every 30–60 seconds until STATUS = READY)
SHOW CORTEX SEARCH SERVICES LIKE 'ECONOMIC_RAG_SEARCH';